### ISSUE TITLE
New orb release should also create a github release from tag

### ISSUE THREAD

**Issue by dsayling** [CircleCI-Public/orb-tools-orb#101]
A tag is automatically pushed to github, which is great, but it would be more helpful is there were releases as well. 
Sadly, this is not a 'git' function, but rather a github function.
There is a way with the cli as of August https://github.com/cli/cli/pull/1552

**Comment by gmemstr** [comment]
@dsayling I have a feeling this is a bit out of scope of the orb. Between installing the GitHub CLI or calling the API directly, I would rather call the API directly, but that would require adding authentication for GitHub in either case, and is a lot of additional overhead.

**Comment by dsayling** [comment]
Do you have a suggestion on how we should publish a gh release to a freshly pushed tag across all the orbs? This is something we need to unify across the orbs. Some repos have releases, others do not. Some have an old release as the latest.
If we don't want to add it to this orb, we could setup a github action that does this?

**Comment by gmemstr** [comment]
Would you mind passing along a link or two with orbs that did/do this? I know many push tags, but I'm not aware of any that create GitHub releases.

**Comment by dsayling** [comment]
I know the python orb has one 'release' https://github.com/CircleCI-Public/python-orb/releases/tag/0.2.2
And the ruby orb https://github.com/CircleCI-Public/ruby-orb/releases

I was thinking, what if we included the logical diff of the orb in the releases here?

**Comment by felicianotech** [comment]
> what if we included the logical diff of the orb in the releases here?

This is the only reason I'd see orb GitHub Releases useful.

**Comment by gmemstr** [comment]
Larger conversation happening around a potential orb tools rework, especially when it comes to versioning and more directly linking git tags <-> orb versions.
