### ISSUE TITLE
Allow passing DockerHub credentials to jobs

### ISSUE THREAD

**Issue by blimmer** [CircleCI-Public/orb-tools-orb#103]
## What would you like to be added

We'll need a way to pass the `auth` block to the `docker` configuration parameter ([docs](https://circleci.com/docs/2.0/configuration-reference/#docker)) for `job`s used directly in `workflows`.

## Why is this needed

Starting November 1, 2020, DockerHub will [begin rate-limiting image pulls from DockerHub](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/). Users need a way to pass their DockerHub credentials to avoid the rate limit. Without providing this configuration option, deployments from CircleCI will be impacted.

**Comment by gmemstr** [comment]
CircleCI has partnered with Docker Hub and will not be subject to rate limiting - you can read more here: https://support.circleci.com/hc/en-us/articles/360050623311-Docker-Hub-rate-limiting-FAQ
