### ISSUE TITLE
v10.0.1 does not process includes in the pack step correctly

### ISSUE THREAD

**Issue by bisrael** [CircleCI-Public/orb-tools-orb#104]
Even though the circleci cli locally will pack this project just fine, the cli included with the orb-tools orb does not.

Please see this example:

https://app.circleci.com/pipelines/bitbucket/roadstruck/orb-honk-base/22/workflows/12bfcfc7-d195-499a-9873-2b531572005f

Src here: https://bitbucket.org/roadstruck/orb-honk-base/branch/slack

**Comment by dsayling** [comment]
@bisrael there was a bug in a recent release of the cli, the change has been reverted. could you verify this is still an issue?

**Comment by gmemstr** [comment]
The bug in question was with the string matching when we replace the values - dashes in filenames were not matched correctly :)

**Comment by gmemstr** [comment]
Consdering this fixed.
