### ISSUE TITLE
Problems with parallel development of the orb

### ISSUE THREAD

**Issue by antonlisovenko** [CircleCI-Public/orb-tools-orb#119]
Hi.

We see some issues raising when more than one person is working on the orb on the same time.

Example:
- user A creates a PR and adds command X. Adds tests for it and makes sure the CI "sees" the new command
- user B creates another PR and makes non-related changes, runs a CI job
- user A triggers job again and gets the config validation error "command X is not known". To fix this they need to disable integration test, build the dev orb again, then enable the tests again.

Am I right that each job triggered checks the "dev" orb published by the **previous** workflow only? So if there was some transient orb without the new command - an engineer will have to rebuild the dev job again?

Thank you

**Comment by KyleTryon** [comment]
Hey @antonlisovenko,

Sorry for the long delay here. This will no longer be an issue from Orb Tools v11 onward as each pipeline will run based on the SHA specifically rather than any tag.
