### ISSUE TITLE
Unable to publish orb correctly; blocking development

### ISSUE THREAD

**Issue by katebygrace** [CircleCI-Public/orb-tools-orb#122]
Newly published version of orb does not contain the code newly added commands. The commands exist if you SSH in, and on https://circleci.com/developer/orbs/orb/stavvy-orb/stavvy-private-orb (private orb, visibility may be limited). But they are not able to be called. Calling 1.8.4 should call a lot more steps than it does. It's calling the steps from 1.5.11. But the page is updated. 

This is blocking a fix for some mission critical tasks, including deploys. Any urgency would be appreciated.

**Comment by KyleTryon** [comment]
Hello,

This was likely due to a mismatch between what existed on CircleCI and what existed within your codebase. This can be resolved by running this command:

```shell
circleci orb pack src orb.yml
circleci orb publish orb.yml <namespace>/<orb-name>@dev:alpha
```

We will be publishing #111 momentarily which should not run into this same type of issue and includes a migration guide for updating.
