### ISSUE TITLE
deprecation warning

### ISSUE THREAD

**Issue by wyardley** [CircleCI-Public/orb-tools-orb#130]
## Orb version:
11.1.0

## What happened:
error
You’re using a [deprecated Docker convenience image.](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034) Upgrade to a next-gen Docker convenience image.
displays in UI

## Expected behavior:
Error should not display

## Additional Information:
I know that this is actually caused by
https://github.com/CircleCI-Public/circleci-cli-orb/issues/16
but creating a bug here as well for visibility

**Comment by KyleTryon** [comment]
We are working to get the CircleCI CLI image update and will push a fix shortly with a pinned version. Thank you!

**Comment by wyardley** [comment]
@KyleTryon any news on this?

**Comment by KyleTryon** [comment]
Not yet @wyardley, I have created a ticket with the appropriate team. I will send them a ping for urgency.

**Comment by KyleTryon** [comment]
Issue has been resolved
