### ISSUE TITLE
Allow orb-tools/review RC009 to have a customized character length

### ISSUE THREAD

**Issue by hannahkamundson** [CircleCI-Public/orb-tools-orb#151]
## Describe Request:
Right now `orb-tools/review` `RC009` will fail a job if it is over 64 characters. Our organization would like to customize that number so we can make the character limit larger. 

## Supporting Documentation Links:
https://circleci.com/developer/orbs/orb/circleci/orb-tools#jobs-review
https://github.com/CircleCI-Public/orb-tools-orb/blob/6a148422095c99ba9c0995016d27b82fe89f862f/src/scripts/review.bats#L166

**Comment by KyleTryon** [comment]
Hey @hannahkamundson thanks for sharing this, it makes sense. Do you have any thoughts on how you would like to set this option?

The easiest solution is to add parameters to the job although i do worry we could end up with a lot of them.

```
- orb-tools/review:
    RC009_COMMAND_LENGTH: 123
```

A side question, are you looking to remove the limit or change it to something longer? What is your ideal length?
