### ISSUE TITLE
Support self-hosted server on orb-tools/publish

### ISSUE THREAD

**Issue by rprince-anduril** [CircleCI-Public/orb-tools-orb#157]
## Describe Request:
Support self-hosted server on orb-tools/publish

## Examples:
We use GitHub Enterprise with self-hosted circleci. We import public orbs to our repository and we need to provide --host options to `circleci orb publish`.

## Supporting Documentation Links:
https://support.circleci.com/hc/en-us/requests/113245

**Comment by rprince-anduril** [comment]
Possible implementation in PR #156

**Comment by KyleTryon** [comment]
Now available in https://github.com/CircleCI-Public/orb-tools-orb/releases/tag/v11.3.0
