### ISSUE TITLE
RC008: Fails when using `cimg/base:current`

### ISSUE THREAD

**Issue by Gaardsholt** [CircleCI-Public/orb-tools-orb#176]
## What happened:
I get this error `RC008: All Run steps should contain a name.`
And below is a small snippet of the errors(basically all of our files)

```
(in test file review.bats, line 141)
  `exit 1' failed
File: "./src/jobs/build_n_push_docker.yml"
Line number: 0
---
null
---
File: "./src/jobs/build_n_push_docker.yml"
Line number: 0
---
null
---
File: "./src/jobs/build_n_push_docker.yml"
Line number: 0
---
null
---
```

## Expected behavior:

It should work.

## Additional Information:

If I downgrade to and earlier version of the executor, it will work again

This **doesn't** works
```yaml
- orb-tools/review
```

This **does** works
```yaml
- orb-tools/review:
    tag: "2022.11"
```

**Comment by inkbeard** [comment]
I'm getting this same issue the work around works. Thanks @Gaardsholt

**Comment by KyleTryon** [comment]
Hey folks, thank you for reporting this and sorry for the issue! We just quickly pushed a patch and you should no longer have this issue. If you do still see the issue, please ensure you are using the latest version of the orb. v11.5.1
