### ISSUE TITLE
Feature: Full support for Private Orbs

### ISSUE THREAD

**Issue by KyleTryon** [CircleCI-Public/orb-tools-orb#179]
# Problem:
There are a few considerations to take into account when publishing private orbs, which differ from the process to public orbs. I am creating this issue to track and discuss all private orb related issues with Orb-Tools so that we might find a common solution.

## Issues:
 - **A** #175 Describes an issue with the `circleci orb validate` command, which fails in private orbs.
 - **B**  #158 Review Check tests which are checking if the URLs in HomeURL and SourceURL are accessible, for private orbs, they may not be accessible.
 - [ Collecting more data, have an issue with private orbs? Let us know here ]

# Solution Discussion

1. Both of the issues above are resolved by adding appropriate parameters to the config.
    -  To validate a private orb, your `CIRCLECI_TOKEN` must be present, which can be resolved by attaching your _restricted_ publishing context to the `pack` job.  [Full comment](https://github.com/CircleCI-Public/orb-tools-orb/pull/175#issuecomment-1348798752)
    -  The Review Check tests `RC006` and `RC008` check for the validity of URLs supplied to the orb's display area. With a private orb, it is expected that the `source_url` tested by `RC006` [Full comment](https://github.com/CircleCI-Public/orb-tools-orb/issues/158#issuecomment-1348938740)
 2. Could both issues be best resolved by improved error messaging?
 3. In the case of **B**, should test RC006 automatically assume the URL is unreachable for private orbs? This would require we inform the review step in some way that the orb is indeed private, possibly through a parameter.
     - It could be helpful to store as a _project level_ environment variable, something such as `isPrivate=true`. However, if this is currently only helpful for the RC006 test, I think it may not be a worthy change yet.
     - It looks like form #142 there are at least a few users who are looking for this to be skipped "automatically".

**Comment by KyleTryon** [comment]
In response to Solutions, section 3.
> should test RC006 automatically assume the URL is unreachable for private orbs?

As stated in this comment, we could specify an environment variable which specifies the orb is private. This environment variable could be automatically set with the `orb init` command in the CircleCI CLI as a part of the initialization process. The users could still manually resolve issues but we may be able to use the metadata to offer better error messaging or automated configuration.

**Comment by adamdmharvey** [comment]
Throwing a random idea out: What about elevating some metadata about the private nature of the orb into the `@orm.yml`?  Obviously, at the moment that's assumed to be a standard set of orb metadata, and the only thing triggering an orb to be private is the commands I fire at the CLI to make it public or private or not.

Perhaps there needs to be an additional  level of metadata, such that a key/value pair should be in the metadata that's checked against the permissioning.  Say there was a value in the `@orb.yml` file, maybe `visibility: private`, and if the orb is being published a PUBLIC, there's a warning and a failure. (possibly one you could "accept" with a CLI flag?)

otherwise, it sort of feels like all of this "external" stuff i have to go to make it go private - i have to call the CLI differently when setting it up, (with the proposal) i have to add an environment variable to my build pipeline, etc.  why add all these things if they could be part of the metadata and then automation could infer it?

**Comment by KyleTryon** [comment]
@adamdmharvey I somewhat agree. We actually wanted to do this back when we added the `display` key which includes your source url and home url, which didn't originally exist. I actually voted to call the key `metadata`. The issue is, orb config _is_ CircleCI config, so anything that would become part of the orb source code, needs to be valid CircleCI config. That said, we could _potentially_ strip that information out of the `@orb.yml` file when packing.

**Comment by adamdmharvey** [comment]
Thanks for the work, Kyle & team !

**Comment by tdeekens** [comment]
@KyleTryon quick question. Orb-tools still seems to pull in `0.1.26094` through the Docker executor. If we bump that to `0.1.26343` passing org id and slug should work, right? Right now on it fails with orb-tools as the version of the CLI being pulled in doesn't support it yet.

**Comment by tdeekens** [comment]
> I assume you were trying to take advantage of envsubst?

No not really. Mainly given the default executor of the Orb pulling in `0.1.26094` [here](https://github.com/CircleCI-Public/orb-tools-orb/blob/master/src/executors/default.yml#L7) by default means by default `orb-tools` doesn't support private Orbs using private Orbs unless I am missing something.

**Comment by KyleTryon** [comment]
Ah no you are not wrong! Thank you @tdeekens. This is why we previously were not pinned to a tag, we'll need to issue a quick patch. Great call out thank you. Orb tools v12.0.1 incoming

**Comment by tdeekens** [comment]
> Ah no you are not wrong! Thank you @tdeekens. This is why we previously were not pinned to a tag, we'll need to issue a quick patch. Great call out thank you. Orb tools v12.0.1 incoming

Thanks I was already wondering if I live twice as I was quite sure it was `latest` once 🐱 .

**Comment by tdeekens** [comment]
Thanks for the quick release. I am getting this error when publishing and I fail to trace it's origin. Can you help?

<img width="1031" alt="CleanShot 2023-05-10 at 17 08 55@2x" src="https://github.com/CircleCI-Public/orb-tools-orb/assets/1877073/3cb6232c-48f0-4707-9c89-0a278a545e49">

**Comment by tdeekens** [comment]
Thanks. Maybe just an error then in adjusting the parameter names.
