### ISSUE TITLE
ORB_RELEASE_VERSION not correct when patch version greater than 9

### ISSUE THREAD

**Issue by djenniex-gg** [CircleCI-Public/orb-tools-orb#182]
## What happened:

Created a new tag for a release called v0.0.25. However, the tag was shortened to v0.0.2 during the orb-tools-publish job.

```
Preparing to publish your orb.
Production release detected!
Production version: 0.0.2
```

## Expected behavior:

Orb should have been released with the v0.0.25 tag.

## Additional Information:

Looks like the regex in the [publish.sh](https://github.com/CircleCI-Public/orb-tools-orb/blob/master/src/scripts/publish.sh#L57) is not greedy enough and only takes the first number.

**Comment by KyleTryon** [comment]
Resolved in #183 Thank you 🙏
