### ISSUE TITLE
Clarify the CircleCI Base Docker image - current or intentionally pinned for stability?

### ISSUE THREAD

**Issue by adamdmharvey** [CircleCI-Public/orb-tools-orb#189]
## Describe Request:

The review job indicates that the "most current stable release" of the CircleCI Docker image will be used if not explicitly overwritten.

https://github.com/CircleCI-Public/orb-tools-orb/blob/3643c8f3bf2d022f3477b142ffd87a5981a5666d/src/jobs/review.yml#L33

However, the job hardcodes a specific year/month published version. As of today, for example, 2023 Jan 11, it's defined as `2022.12-18.04` so it's the Dec 2022 version of Ubuntu 18.

https://github.com/CircleCI-Public/orb-tools-orb/blob/3643c8f3bf2d022f3477b142ffd87a5981a5666d/src/jobs/review.yml#L31

However, the latest is `current` tag in DockerHub is Jan 2023 - likely including newer OS patches.

I wasn't sure if a) it was intentional to pin this to help keep the orb-tools stable, or if in fact b) to suit the description of the job, the default tag should be changed to `current-18.04` (if not `current-20.04`).

So wanted to open this issue for dialog with the community.  The outcome would either be a trivial update to the description, or a trivial update to the tag. 😁 

## Examples:

https://github.com/CircleCI-Public/orb-tools-orb/blob/3643c8f3bf2d022f3477b142ffd87a5981a5666d/src/jobs/review.yml#L29-L34

## Supporting Documentation Links:

https://circleci.com/developer/orbs/orb/circleci/orb-tools#jobs-review
https://circleci.com/developer/images/image/cimg/base#image-tags

**Comment by KyleTryon** [comment]
Great call 👍 Looking into this now and will update #181
