### ISSUE TITLE
trigger-integration-workflow makes superflous use of `add_ssh_keys`

### ISSUE THREAD

**Issue by cfra** [CircleCI-Public/orb-tools-orb#23]
### Orb version

8.3.0

### What happened

Documentation shows that an ssh fingerprint needs to be specified with `ssh-fingerprints` to be then added to the executor with `add_ssh_keys`.

Adding the ssh key via `add_ssh_keys` is unnecessary. To quote from the [documentation](https://circleci.com/docs/2.0/add-ssh-key/):

> Even though all CircleCI jobs use `ssh-agent` to automatically sign all added SSH keys, you *must* use the `add_ssh_keys` key to actually add keys to a container.

For pushing to Git(hub) via SSH, it is completely sufficient to have the key available for signing in `ssh-agent`. There is no need to add the actual private key file to the container.

### Expected behavior

The use of `add_ssh_keys` should be optional, as should be the associated `ssh-fingerprints` parameter.

This also allows for people using other means of authentication like for example Github tokens.

**Comment by iynere** [comment]
@cfra i'm fairly certain that's not the case, & that w/o these steps, the intended functionality breaks.... our keys by-default are read-only, so we certainly need to add a new key with read/write privileges

**Comment by iynere** [comment]
ya, just verified, without the ssh fingerprint, you lose `push` access back to the GH repo @cfra https://circleci.com/gh/CircleCI-Public/orb-tools-orb/781

**Comment by cfra** [comment]
Looking at the error message, you can see it is authenticating with the wrong key. If you delete the read-only key from Github and leave only the read-write key which you have configured for your CircleCI project, it will work just fine.

**Comment by iynere** [comment]
sure, you could delete the read-only key, but that's the default key added automatically by circle... seems like not a good practice to remove it. the whole point of this is that we're adding a read/write key, which is more permissive, & we're adding it _manually_ because we don't _always_ need it—we only need it for specific tasks like this @cfra

**Comment by iynere** [comment]
@cfra i hear that. feel free to submit a PR adding a param to make it optional—please leave the default value `true`, though
