### ISSUE TITLE
integration test design in documentation is prone to race conditions

### ISSUE THREAD

**Issue by cfra** [CircleCI-Public/orb-tools-orb#24]
### Orb version

8.3.0

### What happened

The orb under test is referenced as `orb@dev:alpha`.

If I push two feature branches at once, it is quite possible that workflows will run in the following sequence:

- `lint_pack-validate_publish-dev-branch-1`
- `lint_pack-validate_publish-dev-branch-2`
- `integration-tests_prod-release-branch-1`
- `integration-tests_prod-release-branch-2`

In that case, `integration-tests_prod-release-branch-1` will actually run the tests against `branch-2`.

Even worse, if I push `master` and a feature-branch at the same time, there is the possibility that the orb built from the feature-branch will be confused with the orb from the master branch, and is subsequently promoted to a release.

**Comment by iynere** [comment]
@cfra you can use something like this to mitigate these kinds of issues

https://github.com/eddiewebb/circleci-queue

& tbh, regular commits / jobs / workflows on CircleCI are prone to the same issues

**Comment by iynere** [comment]
> Even worse, if I push master and a feature-branch at the same time, there is the possibility that the orb built from the feature-branch will be confused with the orb from the master branch, and is subsequently promoted to a release.
this is not true, at least by default, as the `dev-promote-prod` job by default promotes only the `dev` orb published with the same specific git `sha` of the commit that triggered the workflow:

https://github.com/CircleCI-Public/orb-tools-orb/blob/master/src/jobs/dev-promote-prod.yml

**Comment by cfra** [comment]
Thank you for pointing to `circleci-queue`, this certainly looks interesting, I will have a closer look. :eyes:
Also, thank you for clarifying how the promotion is working. :pray:
