### ISSUE TITLE
Add option to never automatically publish major releases

### ISSUE THREAD

**Issue by iynere** [CircleCI-Public/orb-tools-orb#31]
make auto-publish feature better conform to SemVer specifications (i.e., major release should only happen for breaking changes)—

instead of automating major releases, only automate minor / patch releases, & create an alternative mechanism in orb-tools for automating major releases (e.g., push a particular git tag, push to a specially named branch, etc.)

**Comment by DallasO** [comment]
Isn't this the current functionality?
https://github.com/CircleCI-Public/orb-tools-orb/blob/6eb2eeaa6d549110ac4bd7ed4b4a751627e1433e/src/jobs/trigger-integration-workflow.yml#L148-L163

**Comment by lokst** [comment]
Closing this as the issue is already resolved
