### ISSUE TITLE
container image used by the lint job doesn't contain git

### ISSUE THREAD

**Issue by simonpasquier** [CircleCI-Public/orb-tools-orb#34]
### Orb version

8.14.0

### What happened

I wanted to publish my orb to the registry when a tag is pushed. It happened that the `checkout` step for the `orb-tools/lint` job failed systematically and I noticed that the `singapore/lint-condo` image doesn't have `git` installed.

```
Either git or ssh (required by git to clone through SSH) is not installed in the image. Falling back to CircleCI's native git client but the behavior may be different from official git. If this is an issue, please use an image that has official git and ssh installed.
Enumerating objects: 136, done.
Counting objects: 100% (136/136), done.
Compressing objects: 100% (74/74), done.
Total 136 (delta 45), reused 125 (delta 43), pack-reused 0

object not found
```

https://circleci.com/gh/simonpasquier/prometheus-orb/96

I've worked around the issue by not running the `lint` job on tags. Which is mostly fine as the linting already happened when merging to master.

### Expected behavior

No checkout error in the lint job.

**Comment by iynere** [comment]
@simonpasquier you can always use `pre-steps` to, for example, quickly install git:

https://circleci.com/docs/2.0/reusing-config/#using-pre-and-post-steps

that said, the source of the `orb-tools/lint` job runs `checkout` automatically & this typically works for our repos—our `checkout` step is not actually dependent on `git`

**Comment by iynere** [comment]
@simonpasquier what does seem like a good option, though, is making the executor for `lint` customizable, so if you want to use a different docker image, you can. i'll do that right away.

**Comment by iynere** [comment]
change made in `circleci/orb-tools@8.16.0` @simonpasquier

**Comment by simonpasquier** [comment]
Thanks for the quick response! As I said, I wasn't blocked by this but having a way to override the image is always nice...
