### ISSUE TITLE
lint fails on annotated tag

### ISSUE THREAD

**Issue by sudermanjr** [CircleCI-Public/orb-tools-orb#45]
### Orb version

v8.27.3

### What happened

An annotated tag cannot be checked out by the default Circle git client.  This build https://circleci.com/gh/FairwindsOps/rok8s-scripts/2020 failed due to this fact.

### Expected behavior

All other branch builds work fine.  I would expect an install of a fully-fledged git client as part of the lint image.

**Comment by sudermanjr** [comment]
Looks like I might be able to workaround this with something like this:

```
          pre-steps:
            - run:
                command: apk add git

```

Seems a little strange to need to override this, especially considering how often annotated tags are used.

**Comment by iynere** [comment]
@sudermanjr the lint job is designed to be run on branches, mostly, but the `pre-steps` you identified seem like a good workaround. feel free to submit a par to always `apk add git openssh` or something like that if you feel it would be a good addition. thanks!
