### ISSUE TITLE
Feature Idea: Enable shell scripts to be pre-processed into orb commands

### ISSUE THREAD

**Issue by jrnail23** [CircleCI-Public/orb-tools-orb#47]
Just an idea here...
I _HATE_ writing significant shell commands in yaml.  I always make typos, and the lack of syntax highlighting is a drag.

So here's an idea: what if we could write some of our commands in a `.sh` file, then pre-process them into our orb's commands, with args mapped to the command's parameters?

That way, we could even use something like `shellcheck` to validate our scripts before processing.

**Comment by KyleTryon** [comment]
Hard to give an exact timeline but I am going to try to get to this soon.

**Comment by KyleTryon** [comment]
@jrnail23 

Simultaneously beginning to explore your original idea more in-depth. Do you have any vision of how you would expect that to look like?

So given we have a current structure such as:


> /
> -- src/
> -- -- @orb.yml
> -- -- commands/
> -- -- -- myCommand.yml
> -- -- jobs/
> -- -- executors/


Where would be the best place to reference scripts from and how would you like that to look when writing your orb?

My initial thought is to go simple, with something like this:

We might theoretically have a special `orb pack command` which would intelligently pack our orb for us.


> /
> -- src/
> -- -- @orb.yml
> -- -- commands/
> -- -- -- myCommand.yml
> -- -- jobs/
> -- -- executors/
> -- -- **scripts**/
> -- -- -- **myScript.bash**

Within an orb command's source, I imagine this could look like:

```
description: "This command was built with orb packing"

parameters:
  ...
steps:
  - run:
      name: "Long complex task"
      command: << scripts.myScript >>
```

Which after packing would expand to include the bash source directly within the command.

Another major benefit I see here is the ability to remove what we have previously called "internal" commands or "plumbing" commands. There are some orbs which have commands which are not truly meant to be used by the end-user but are created so they could be used within multiple other commands or jobs. With this addition, the user could reference the same script twice.

That would result in the code being "duplicated" in the processed result but I think it is still a better outcome.

CC @felicianotech (we were just talking about this)

**Comment by jrnail23** [comment]
@KyleTryon, what you're saying here about the special packing behavior is just what I had in mind.
I think one thing you didn't yet touch on is mapping parameters from the command to the script.
With a decent declarative way to do that (I really hate positional params -- it's so easy to screw them up when you're refactoring), I think this would be a killer feature.

**Comment by gmemstr** [comment]
@jrnail23 We're nearing completion of a command within the CLI do to exactly this, I would be more than happy to grab a compiled binary for you to test. Otherwise you can build it yourself from this branch :) https://github.com/CircleCI-Public/circleci-cli/tree/orb-pack

**Comment by jrnail23** [comment]
@gmemstr, this is great news. Thanks!

**Comment by jrnail23** [comment]
@gmemstr, I think I'd like to take you up on your offer of a compiled binary... I figured I'd do it myself, but then I remembered how lost I am in GoLang world!

**Comment by gmemstr** [comment]
@jrnail23 I'm working on getting built binaries for an open beta, I'll be sure to ping you when they're ready!

**Comment by gmemstr** [comment]
@jrnail23 You can find more information here :) https://discuss.circleci.com/t/circleci-cli-orb-pack-beta/36598

**Comment by jrnail23** [comment]
@gmemstr, is the expectation that we'd pass in params like this?
```
- run: << include(scripts/hello-world.sh) >> "<<parameters.param0>>" "<<parameters.param1>>"
```

**Comment by KyleTryon** [comment]
Just some maintenance, closing this up as we do have this now 👍 
Read more here: 
- https://circleci.com/docs/2.0/orb-concepts/?section=configuration#file-include-syntax
- https://circleci.com/docs/2.0/orb-author/
