### ISSUE TITLE
New job for not using destructured yaml

### ISSUE THREAD

**Issue by DallasO** [CircleCI-Public/orb-tools-orb#59]
## Orb version

8.27.4

### What happened

Orb workflow indirectly forces use of destructured yaml. 

### Expected behavior

It should be just as easy to use a single orb file as it is to use destructured yaml

The example  in the [README](https://github.com/CircleCI-Public/orb-tools-orb/blob/master/README.md) uses the *Lint* - *Pack* - *Publish-Dev* - etc workflow. The Pack job expects a destructured yaml to be... well, destructured. So if someone creating a new Orb only has a single `orb.yaml` file, now they have to figure out how to move that file and persist it so that the *Publish-Dev* step can use it. 

I'm requesting a job to `not-pack`, where it takes `orb.yaml` or an `orb-path` param and does the same persist to workspace magic that `pack` does. To be easier for newcomers.

**Comment by lokst** [comment]
Thanks @DallasO , that would be a great enhancement!

**Comment by gmemstr** [comment]
It does _sort of_ support structured orb.yml files. We currently use the `config pack` CLI command, which walks directories and searches for .yml files and then combines them. Theoretically, one could indicate `.` is the "source" directory, and the CLI will pick up the orb.yml file and pack that. This will change when https://github.com/CircleCI-Public/circleci-cli/pull/432 is merged though.
