### ISSUE TITLE
push git tag after `orb-tools/increment`

### ISSUE THREAD

**Issue by sue445** [CircleCI-Public/orb-tools-orb#7]
Hello. 

I want to push the same tag as the orb'version

e.g.

```bash
#!/bin/bash -eo pipefail
circleci orb publish increment packed/orb.yml sue445/my-orb patch --token $CIRCLECI_API_TOKEN 
Orb `sue445/bundle-install` has been incremented to `sue445/my-orb@1.2.3`.
Please note that this is an open orb and is world-readable.

#### I want to run this!
# git tag -a 1.2.3 -m "Release 1.2.3"
# git push origin --tags
```

But there is no way to acquire the automatically incremented version 😢 

Do you have a good idea or feature?

# My workaround
https://github.com/sue445/circleci-orb-bundle-install/blob/0.1.0/.circleci/config.yml#L114-L125

Running `orb-tools/publish` when only pushed tag.

Although this works, but dirty way...

**Comment by ndintenfass** [comment]
You could run `circleci orb info` to get the latest in an additional step in your flow -- you might need to parse the payload manually, though it's probably a good idea we add some kind of flag to get just the version by itself.

**Comment by sue445** [comment]
@ndintenfass Thank you! I'll try this.
