### ISSUE TITLE
skip tag if skip publish in orb-tools/dev-promote-prod-from-commit-subject

### ISSUE THREAD

**Issue by nik-shornikov** [CircleCI-Public/orb-tools-orb#76]
the way it currently sits `publish-version-tag: true` in this job will attempt to add a tag even if `[semver:skip]` was present; it seems unlikely that someone would attempt to do that on purpose: promote nothing but tag the code (i think the tag is meant to capture the exact revision which was promoted)
this is a problem because in lieu of an increment, the tag is always already there and `git push origin "$TAG"` fails
another way of putting that is that `publish-version-tag: true` is only technically compatible with skipping a version bump -- out in the wild, it won't be

**Comment by nik-shornikov** [comment]
https://github.com/CircleCI-Public/orb-tools-orb/blob/e302710073ca365243bf990bfe3dfb66573843a1/src/jobs/dev-promote-prod-from-commit-subject.yml#L128-L134

**Comment by lokst** [comment]
@nik-shornikov Thanks for describing the problem so clearly!
