### ISSUE TITLE
Mismatch in default CircleCI auth token environment name

### ISSUE THREAD

**Issue by jlenos-inflight** [CircleCI-Public/orb-tools-orb#83]
There seems to be a mismatch between the default CircleCI auth token environment name for this orb (CIRCLE_TOKEN) and the official default one for the cli (CIRCLECI_CLI_TOKEN).

https://circleci-public.github.io/circleci-cli/index.html
https://circleci.com/orbs/registry/orb/circleci/circleci-cli

**Comment by gmemstr** [comment]
I believe it would be easier to move the CLI orb to the `CIRCLE_TOKEN` naming scheme, but I would hesitate to do so given the potential impact it could have on people's builds. This might be something worth revisiting down the line, but I don't see this as an issue - feel free to correct me though :)
