### ISSUE TITLE
Current examples reference non-existent shellcheck job

### ISSUE THREAD

**Issue by dijitali** [CircleCI-Public/orb-tools-orb#99]
The v10.0.0 examples reference a orb job called shellcheck but it doesn't seem to be available:
https://circleci.com/orbs/registry/orb/circleci/orb-tools?version=10.0.0#usage-examples

When the example is used, I get a `Cannot find a definition for job named orb-tools/shellcheck` error:
![image](https://user-images.githubusercontent.com/4665045/91578083-975fb780-e941-11ea-9bd2-ebc46cff2183.png)

Not sure if this is a bug with the example and we should be using the https://circleci.com/orbs/registry/orb/circleci/shellcheck orb directly, or if the job was incorrectly removed from this orb with v9 => v10 release?

**Comment by dijitali** [comment]
Ah just spotted https://github.com/CircleCI-Public/orb-tools-orb/pull/93 where this was discussed, sounds like we should be using that new separate shellcheck orb now.

**Comment by orb-publisher** [comment]
$PR_MESSAGE

**Comment by orb-publisher** [comment]
$PR_MESSAGE

**Comment by orb-publisher** [comment]
$PR_MESSAGE

**Comment by orb-publisher** [comment]
$PR_MESSAGE

**Comment by orb-publisher** [comment]
$PR_MESSAGE

**Comment by orb-publisher** [comment]
$PR_MESSAGE

**Comment by orb-publisher** [comment]
$PR_MESSAGE

**Comment by orb-publisher** [comment]
$PR_MESSAGE

**Comment by orb-publisher** [comment]
$PR_MESSAGE

**Comment by orb-publisher** [comment]
$PR_MESSAGE

**Comment by orb-publisher** [comment]
$PR_MESSAGE

**Comment by orb-publisher** [comment]
$PR_MESSAGE

**Comment by orb-publisher** [comment]
$PR_MESSAGE

**Comment by orb-publisher** [comment]
$PR_MESSAGE

**Comment by orb-publisher** [comment]
$PR_MESSAGE

**Comment by orb-publisher** [comment]
$PR_MESSAGE

**Comment by orb-publisher** [comment]
$PR_MESSAGE
